
hdfs:
  url: "http://namenode:9870"  # utilisé pour InsecureClient
  path: "/dataflow360/raw/"
  host: "dataflow360_namenode"
  port: 9870

elasticsearch:
  host: "http://elasticsearch:9200"
  index: "kafka_flow360"
