
input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["data_stream"]
    group_id => "hdfs_loader" 
    # Optional configurations:
    auto_offset_reset => "latest" 

  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "kafka_flow360"
  }
}